/*

	SQL_AGENT_DATA_MART T-SQL scripts

*/

USE [master]
GO


-- create database if it doesn't exist
IF DATABASEPROPERTYEX (N'SQL_AGENT_DATA_MART', N'Version') IS NULL
BEGIN
	CREATE DATABASE [SQL_AGENT_DATA_MART];

END
GO


ALTER DATABASE [SQL_AGENT_DATA_MART]
SET RECOVERY SIMPLE;
GO


USE [SQL_AGENT_DATA_MART]
GO


IF NOT EXISTS (
	SELECT 1 
	FROM sys.sequences
	WHERE [name] = 'RefreshKey'
)
BEGIN
	CREATE SEQUENCE [dbo].[RefreshKey]  
		START WITH 1  
		INCREMENT BY 1;  
END
GO  


CREATE OR ALTER PROCEDURE [sqlagent].[SimulateJobStepDuration]
	@MINIMUM_MINUTES	INT = 1
,	@MAXIMUM_MINUTES	INT = 10
AS
BEGIN
	-- convert to range of seconds
	DECLARE
		@MINIMUM_SECONDS		INT = @MINIMUM_MINUTES * 60
	,	@MAXIMUM_SECONDS		INT = @MAXIMUM_MINUTES * 60
	,	@STEP_DURATION_SECONDS	INT = 0
	,	@WAIT_FOR				VARCHAR(10);

	WHILE @STEP_DURATION_SECONDS < @MINIMUM_SECONDS
	BEGIN
		SET @STEP_DURATION_SECONDS = FLOOR(RAND() * @MAXIMUM_SECONDS);
	END

	SELECT @STEP_DURATION_SECONDS;

	--WAITFOR DELAY = '00:05';
END




	




